[package]
name = "discographer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
lofty.workspace = true
walkdir.workspace = true
serde.workspace = true
tracing.workspace = true
camino = "1.1"

[dev-dependencies]
