[package]
name = "discographer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
lofty.workspace = true
serde.workspace = true
serde_json.workspace = true
soundstore.workspace = true
tracing.workspace = true
walkdir.workspace = true

[dev-dependencies]
tempfile = "3.23.0"
criterion = { workspace = true }

[[bench]]
name = "scan"
harness = false
